### ISSUE TITLE
Error when overwriting stderr

### ISSUE THREAD

**Issue by swt30** [randy3k/rchitect#10]
In radian, printing a carriage return character `\r` to stderr causes an error to be thrown from rchitect:

```
r$> write("\r", stderr())                                                                                          
From cffi callback <function cb_write_console_capturable at 0x105fa17a0>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    console.write_console(text, otype)
  File "/usr/local/lib/python3.7/site-packages/rchitect/console.py", line 23, in write_console
    _callback.write_console_ex(buf, otype)
  File "/usr/local/lib/python3.7/site-packages/radian/console.py", line 85, in write_console_ex
    print_formatted_text(ANSI(stderr_format.format(buf)), end="", file=sys.stderr)
  File "/usr/local/lib/python3.7/site-packages/lineedit/deps/prompt_toolkit/shortcuts/utils.py", line 115, in print_formatted_text
    output, fragments, merged_style, color_depth=color_depth)
  File "/usr/local/lib/python3.7/site-packages/lineedit/deps/prompt_toolkit/renderer.py", line 642, in print_formatted_text
    assert '\r' not in text
AssertionError
```

An example of when you might do this is when monitoring progress with a progress bar:

```
r$> install.packages("progress", quiet=TRUE)                                                                       

r$> pb <- progress::progress_bar$new(total = 100) 
    for (i in 1:100) { 
      pb$tick() 
      Sys.sleep(1 / 100) 
    }

[loads of errors]
```

Let me know if this is easily fixed with PR as I'd quite like to help for Hacktoberfest :)

**Comment by swt30** [comment]
Just saw you fixed this in radian https://github.com/randy3k/radian/commit/9c392ac5d01e09ac8ce309250a536ecf5ad7e70c in release 0.4.2. Thanks!
